# Generated by Django 4.2.19 on 2025-02-26 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=255)),
                (
                    "nacionalidade",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("biografia", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                (
                    "edicao",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Edição"
                    ),
                ),
                ("editora", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "ano_publicacao",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ano de Publicação"
                    ),
                ),
                (
                    "preco_capa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Preço de Capa",
                    ),
                ),
                ("categoria", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livros",
                        to="livros.autor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Estoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[("Entrada", "Entrada"), ("Saída", "Saída")],
                        db_column="tipo",
                        max_length=10,
                    ),
                ),
                ("data", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoque",
                        to="livros.livro",
                    ),
                ),
            ],
        ),
    ]
