# Generated by Django 5.1.2 on 2025-02-22 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='data_entrada',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='livros.livro'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autores',
            field=models.ManyToManyField(related_name='livros', to='livros.autor'),
        ),
    ]
